# Base configs
baseurl: ""
url: "http://photography.dignitasdigital.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-28080872-1"

# UI configs
title: "Photography by Dignitas Digital"
subtitle: "Agency Life"
author: "Dignita Digital"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/dignitasdigital"
  twitter: "https://www.twitter.com/dignitasdigital"
  instagram: "https://www.instagram.com/dignitasdigital"
  linkedin: "https://in.linkedin.com/in/dignitasdigital"
  github: "https://www.github.com/rrais24"
